### ISSUE TITLE
Filesystem has no item while comparing 

### ISSUE THREAD

**Issue by nikhil-github** [rombert/ereviewboard#139] opened 2015-02-10 10:43 UTC
Recently installed ereviewboard and integrated with subclipse . I was able to retrieve the review tasks but when i clicked on file in mylyn rich editor it says  "Filesystem has no item"

**Comment by rombert** [comment] 2015-02-10 19:27
@nikhil-github - thanks for the report. Can you please attach a stack trace?

**Comment by nikhil-github** [comment] 2015-02-10 23:54
Hi Robert , I have enabled the trace but there is just info message 

No stack trace available 
INFO ->
Retrieving file "REPOSITORY FILE LOCATION" @ 1499 from repo null ( "REPOSITORY LOCATION")

Thanks

**Comment by nikhil-github** [comment] 2015-02-11 10:21
Hi Robert , Does this plugin support post commit reviews ?

**Comment by rombert** [comment] 2015-02-11 11:33
> Hi Robert , Does this plugin support post commit reviews ?

No, it does not at the moment

**Comment by rombert** [comment] 2015-02-11 11:33
> Hi Robert , I have enabled the trace but there is just info message 

Do you have anything in the Eclipse error log related to this?

**Comment by nikhil-github** [comment] 2015-02-11 13:45
Hi Robert, There is nothing on the eclipse error log . Only thing it says is that the file revision does not exist in the repo . I noticed that the person who created the review request uses an older version of SVN compared to the one i have . Does this really matters?

**Comment by rombert** [comment] 2015-02-13 23:32
SVN versions _should_ not matter . Some things to try 

- make sure your local checkout is up to date
- try and switching to the same branch as the one on which the review is based

**Comment by nikhil-github** [comment] 2015-02-15 19:07
Hi Robert , thanks for the response . I did update that my local copy is up to date and also tried to switch to the same branch where review board is based but still no luck . I am getting same error window in eclipse that says compare failed with the below message

Failed getting contents of 

https://svn.repository.com/svn/repos/trunk/helloworld.java @1510:
org.apache.subversion.javahl.ClientException:Filesystem has not item
SVN: '/svn/repos/!svn/1533/https:/svn.repository.com/svn/repos/trunk/helloworld.java'
path not found

The only thing i notice is that the second last line for the repo have single slash and not double after the https: . May be something silly but just wanted to let you know.

The strange thing is i am not facing any issues with the review request from our office associates but from offfshore review request none of them are working

Thanks

**Comment by nikhil-github** [comment] 2015-02-15 19:11
One more thing is the users directly create diff files / patch files from eclipse and upload them to review board UI tool to create the review request

**Comment by rombert** [comment] 2015-02-20 09:54
Thanks for the detailed information. I'll have to try and reproduce this, hopefully next week

**Comment by tapasalok** [comment] 2015-03-30 10:10
I am also facing the same issue. Please help me out to fix it.

**Comment by selsemore** [comment] 2015-04-08 09:54
Hi Robert,
I don't know if this is the case here, but I've found that you will get an error like this if the base directory for the patch has been entered as an absolute URL (which is supported from Web UI) rather than as a relative path.  The problem seems to be in SubclipseSCMFileContentsLocator#66:

SVNUrl resourceUrl = repoLocation.getUrl().appendPath(_filePath);

It should be fixed to recognize that _filePath is already a URL and construct the SVNUrl accordingly.

Thanks,
Steve

**Comment by rombert** [comment] 2015-04-09 11:58
Thanks @selsemore for the pull request! I've updated a pre-release at https://github.com/rombert/ereviewboard/releases/tag/ereviewboard-0.13.4-pre-1 . @tapasalok , @nikhil-github - can you please download the zipped update site and check if this fixes your problem?

**Comment by rombert** [comment] 2017-02-19 19:59
No feedback, considering fixed.

**Closed by rombert** 2017-02-19 19:59 UTC
Labels: defect, scm-subclipse
